### ISSUE TITLE
Appears on wrong screen

### ISSUE THREAD

**Issue by niklasb** [Jinmo/ifred#11]
I'm having a hard time building this on my machine or I would try to fix it myself: On Windows, if IDA is opened on a secondary monitor, the palette will still appear on the primary screen, which is a bit counter intuitive :)

**Comment by Jinmo** [comment]
Hello, I've just pushed 4f0eff3 for this issue.
Since I'm currently using one monitor, I might not be able to test it in the exact same environment. Can you check if it works correctly now?

**Comment by niklasb** [comment]
Thanks! I will check it once this dyld_shared_cache finishes loading and I can restart IDA, so probably in like 2 weeks...

**Comment by niklasb** [comment]
Seems to work!
