### ISSUE TITLE
Errors loading ifred

### ISSUE THREAD

**Issue by nyx0** [Jinmo/ifred#14]
Using the following config:

`macOS 10.15.1`
`IDA 7.4` and `IDAPython 3`

I have the following errors while I'm loading IDA with the prebuilt plugins from azure pipelines: 

```
dlopen(~/.idapro/plugins/ida_palette.dylib): dlopen(~/.idapro/plugins/ida_palette.dylib, 2): Symbol not found: _PyBaseObject_Type
  Referenced from: ~/.idapro/plugins/ida_palette.dylib
  Expected in: flat namespace
 in ~/.idapro/plugins/ida_palette.dylib
~/.idapro/plugins/ida_palette.dylib: can't load file

dlopen(~/.idapro/plugins/ida_palette.dylib): dlopen(~/.idapro/plugins/ida_palette.dylib, 2): Symbol not found: __ZN2QT17QAbstractItemView11eventFilterEPNS_7QObjectEPNS_6QEventE
  Referenced from: ~/.idapro/plugins/ida_palette.dylib
  Expected in: flat namespace
 in ~/.idapro/plugins/ida_palette.dylib
~/.idapro/plugins/ida_palette.dylib: can't load file
```

**Comment by Jinmo** [comment]
Oops, I forgot to separate python 3 build for macOS. Thanks for the report!
I just pushed [a fix](https://jinmo123.visualstudio.com/idapkg/_build/results?buildId=165&view=artifacts&type=publishedArtifacts). Unfortunately, I don't have access to mac environment now. Can I request a test?

Thank you.

**Comment by nyx0** [comment]
Sure, I still have the first error:
```
dlopen(~/.idapro/plugins/ida_palette64.dylib): dlopen(~/.idapro/plugins/ida_palette64.dylib, 2): Symbol not found: _PyBaseObject_Type
  Referenced from: ~/.idapro/plugins/ida_palette64.dylib
  Expected in: flat namespace
 in ~/.idapro/plugins/ida_palette64.dylib
~/.idapro/plugins/ida_palette64.dylib: can't load file
```

**Comment by Jinmo** [comment]
Sorry for the late reply. I guess this is related to #8, but it'll still work (even with error above) if the root cause is the same. If you don't mind, can you check if the palette is working? I think this will take some weeks to fix...

Alternatively you can add these lines at `~/.idapro/idapythonrc.py`:

```python
import ida_loader
ida_loader.load_plugin(os.path.expanduser('~/<dylib path>'))
```

**Comment by nyx0** [comment]
No worries, it works indeed. Thank you :)
