### ISSUE TITLE
IDA Pro SP3

### ISSUE THREAD

**Issue by 0xFF1E071F** [Jinmo/ifred#15]
Hello;
I got this error while using IDA Pro SP3:
```
LoadLibrary(C:\<program path here>\IDA 7.5 SP3\plugins\ida_palette64.dll) error: The specified module could not be found.
C:\<program path here>\IDA 7.5 SP3\plugins\ida_palette64.dll: can't load file

LoadLibrary(C:\<program path here>\IDA 7.5 SP3\plugins\ida_palette64.dll) error: The specified module could not be found.
C:\<program path here>\IDA 7.5 SP3\plugins\ida_palette64.dll: can't load file
```

**Comment by Jinmo** [comment]
Hello, are you using python 2 or 3? There is two separated build for each python version in the zip, so please check if you are using the right build.

**Comment by 0xFF1E071F** [comment]
> 
> 
> Hello, are you using python 2 or 3? There is two separated build for each python version in the zip, so please check if you are using the right build.

Thanks for your reply Jinmo.
I have double checked the dll files provided in the release section. Bu t i got the same error. And i am using python3.

**Comment by Jinmo** [comment]
I see, are you using python >3.8? I just checked the binary and then I think it might not work for now if you're using python 3.7 / 3.8.

**Comment by 0xFF1E071F** [comment]
Hello again. I am using Python 3.9.1 right now.

BTW, i have checked my environmental variables(in window$). Python 3.9.1 is on the PATH. And i am not using such environmental variables such as PYTHONHOME or PYTHONPATH. Maybe helpful! 

Thank you.

**Comment by 0xFF1E071F** [comment]
Hello again,
I have download the latest build from the below link:
```
https://jinmo123.visualstudio.com/idapkg/_build/results?buildId=172&view=artifacts&pathAsName=false&type=publishedArtifacts
```
Well, this build is ok on Python version 3.8.

But it is still not working if python version is 3.9

**Comment by Jinmo** [comment]
Hello, can you try https://jinmo123.visualstudio.com/idapkg/_build/results?buildId=173&view=artifacts&pathAsName=false&type=publishedArtifacts ? Thank you.

**Comment by 0xFF1E071F** [comment]
Thank you!
Both Ctrl+P and Ctrl+Shift+P is working right now.
When you open the ida pro it prints `loading palettes...` inside the output window and works like a charm.
If i will encounter any problem iwill open an issue!

**Comment by Jinmo** [comment]
Great! I'll close the issue.
