### ISSUE TITLE
Error loading the DLL

### ISSUE THREAD

**Issue by beauthi** [Jinmo/ifred#16]
Hello,

I tried copying the DLL in my 'plugins' directory, and when loading any file, I get this error :
`LoadLibrary(C:\Users\beauthi\AppData\Roaming/Hex-Rays/IDA Pro\plugins\ida_palette.dll) error: The specified module could not be found.`
I tried Ctrl+Shift+P and Ctrl+P anyway, but both have default behaviors on IDA Pro, which are not ifred.
My configuration : Windows 10, IDA Pro 7.5.

Thank you

**Comment by Jinmo** [comment]
Hello, do you have IDAPython in the environment? Currently it depends on python<version>.dll, but I can add a build without python support if needed.

**Comment by beauthi** [comment]
Yes currently I am using `python36.dll`, I checked the environment variables and it seems to work ! Here is my `sys.path` output :
```
['C:\\Program Files\\IDA Pro 7.5\\python\\3', 'C:\\Program Files\\IDA Pro 7.5\\python\\3\\ida_32', 'C:\\Python36\\python36.zip', 'C:\\Python36\\Lib', 'C:\\Python36\\DLLs', 'C:\\Program Files\\IDA Pro 7.5', 'C:\\Python36']
```
The last element of the list is the actual path where my DLL is stored.
If you have no idea what the problem is, a build without python support would be appreciated ! Thanks :)

**Comment by Jinmo** [comment]
I added a build for python 3.6. Can you try it?

**Comment by beauthi** [comment]
Perfect ! Works like a charm. Huge thanks for your incredible work :)
