### ISSUE TITLE
IDA Pro 7.7 SP1: The specified module could not be found.

### ISSUE THREAD

**Issue by 0xFF1E071F** [Jinmo/ifred#22]
Hello Jinmo

I am using IDA Pro 7.7 SP1 and python 3.10.2 
I have downloaded the latest prebuilt artifacts.
I got this error:
```
LoadLibrary(C:\Program Files\<SNIP>\IDA\plugins\ida_palette64.dll) error: The specified module could not be found.
C:\Program Files\<SNIP>\IDA\plugins\ida_palette64.dll: can't load file
```

Can you provide an artifact for python 3.10 so i can try if that works? Thank you

**Comment by Jinmo** [comment]
Done! b20d8e4

**Comment by 0xFF1E071F** [comment]
I have tested the new binaries and they work like a charm
Thank you @Jinmo ;)
